### ISSUE TITLE
Implement Lighting Player Feedback

### ISSUE THREAD

**Issue by Youg3** [cgl-ma-digital-games-2018/ma1-ggp-assignment#10]
As discussed, implement player feedback through Sound and Lighting
- [x] Lighting trigger when box reaches goal

**Comment by timdhoffmann** [comment]
Are these tasks in the "done" column completely done? if so, you can close the issue from the "three dots" menu icon on the top right of the cards.

**Comment by Youg3** [comment]
They are completely done, provided they worked for you.  Closing now
