### ISSUE TITLE
Menu for direct selection of level

### ISSUE THREAD

**Issue by timdhoffmann** [cgl-ma-digital-games-2018/ma1-ggp-assignment#20]
- [x] Small Level Playable Selector

**Comment by timdhoffmann** [comment]
We had talked about this. Is this still something we want to have?

**Comment by Youg3** [comment]
I'll knock up what I suggested in Discord tonight

**Comment by Youg3** [comment]
Completed.  Set to default.  Awaiting Merge to Dev Branch
