### ISSUE TITLE
Runtime level generation

### ISSUE THREAD

**Issue by timdhoffmann** [cgl-ma-digital-games-2018/ma1-ggp-assignment#7]
- [x] Actors should be placed at runtime
- [x] Information about which actors to place where should be read from file
- [x] Placement of 1x1 wall sections
- [x] Placement of 1x1 boxes
- [x] Placement of box goals
- [x] Placement of player start

**Comment by Youg3** [comment]
I don't know how far you have gotten with this bud, but are we treating this as a submission requirement?

**Comment by timdhoffmann** [comment]
I did some research, yesterday and it's not trivial. I was thinking of trying to get _some_ level generation working (even if the values are hard-coded). Depending on how that goes, I'd see how much I can expand on that in regards to reading the values from file. Are all assets for that ready (so that I can reference them for dynamic instantiation in the level)?
What are all the assets that should be created dynamically?
1. Player start
2. 1x1 walls
3. 1.x1 boxes
4. boxGoals

Did I miss something?

**Comment by Youg3** [comment]
That's a shame.  Was hoping it would be relatively straight forward.  If you do get a hard coded level generator then I think it would be easy to load to from Level 2 to this generated level 3.

For a basic level, I believe the assets are all created, yes.
1. Player Start (actually this is just the Unreal Player Start)
2. 1x1 Wall section is in props
3. uses your box asset
4. uses your box goals

The only thing would be the reading of the end state reached as that's done through blueprints and I don't know if I can make the blueprint for it without the level already made.  But I guess this is low priority to load level 1 afterwards as we just need to show it builds a level from a file.

**Comment by timdhoffmann** [comment]
If you'd like to wire-up the full level flow, you could simply duplicate one of your levels, name it GeneratedLevel00. I would then modify that level later, when I come to working on it.
